import {App} from 'vue'
import Icon from './icons'
import {
    Button,
    Popup,
    Avatar,
    Popconfirm,
    Footer,
    Menu,
    Image,
    Input,
    Form,
    FormItem,
    Space,
    TreeSelect,
    Table,
    BaseTable,
    PrimaryTable,
    EnhancedTable,
    Dialog,
    InputNumber,
    RadioGroup,
    Radio,
    RadioButton,
    Loading,
    Switch,
    Pagination,
    Link,
    Divider,
    Drawer,
    Tag,
    Select,
    Tabs,
    TabPanel,
    Tooltip,
    Tree,
    Textarea,
    Collapse,
    CollapsePanel,
    Upload,
    Checkbox,
    CheckboxGroup,
    InputAdornment,
    CheckTag,
    ColorPicker,
    ImageViewer,
    DateRangePicker,
    Dropdown,
    Row,
    Col
} from 'tdesign-vue-next'
export default (app:App) => {
    app.use(Button)
    app.use(Popup)
    app.use(Avatar)
    app.use(Icon)
    app.use(Popconfirm)
    app.use(Menu)
    app.use(Image)
    app.use(Input)
    app.use(Form)
    app.use(FormItem)
    app.use(Space)
    app.use(Table)
    app.use(BaseTable)
    app.use(PrimaryTable)
    app.use(EnhancedTable)
    app.use(Dialog)
    app.use(TreeSelect)
    app.use(InputNumber)
    app.use(RadioGroup)
    app.use(Radio)
    app.use(RadioButton)
    app.use(Loading)
    app.use(Pagination)
    app.use(Select)
    app.use(Link)
    app.use(Divider)
    app.use(Drawer)
    app.use(Tag)
    app.use(Switch)
    app.use(Tabs)
    app.use(TabPanel)
    app.use(Tooltip)
    app.use(Tree)
    app.use(Textarea)
    app.use(Upload)
    app.use(Collapse)
    app.use(CollapsePanel)
    app.use(Checkbox)
    app.use(CheckboxGroup)
    app.use(InputAdornment)
    app.use(CheckTag)
    app.use(ColorPicker)
    app.use(ImageViewer)
    app.use(Footer)
    app.use(DateRangePicker)
    app.use(Dropdown)
    app.use(Row)
    app.use(Col)
}
